version: '3.6'
services:
  iris:
    build: .
    ports: 
      - 51773
      - ${IRIS_PORT}:52773
      - 53773
    environment: 
      - ISC_DATA_DIRECTORY=/ISC/irisconf.d
    volumes: 
      - ./ISC:/ISC
      - ~/iris.key:/usr/irissys/mgr/iris.key